# Welcome!

#### Pandas: Intro Practice Problems

In this homework, you're going to write code for a few problems. 

You'll be practicing these programming concepts we've covered in class:
* Reading data sets into Pandas.
* Filtering, manipulating, and sorting data sets.
* Basic exploratory data analysis with Pandas.

#### #1. Import Pandas with an alias of `pd`.

In [4]:
import pandas as pd

#### #2. Read in the NBA players `csv` into a variable called `nba_df`.

This is a data set of NBA players from 2015. The filename is `NBA_players_2015.csv`.

In [7]:
nba_df=pd.read_csv('NBA_players_2015.csv')

#### #3. Look at the first five rows of the data set.

In [9]:
nba_df.head()

,Unnamed: 0,season_end,player,pos,age,bref_team_id,g,gs,mp,fg,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
0,0,2015,Quincy Acy,F,24,NYK,52,21,19.2,2.2,...,15.1,14.7,0.6,0.5,1.0,0.050,-2.6,-0.7,-3.4,-0.3
1,1,2015,Jordan Adams,G,20,MEM,18,0,7.3,1.0,...,15.9,17.7,0.0,0.2,0.2,0.076,-2.3,1.8,-0.5,0.0
2,2,2015,Steven Adams,C,21,OKC,51,50,24.2,3.0,...,19.2,14.8,1.0,1.8,2.8,0.109,-2.0,2.0,-0.1,0.6
3,3,2015,Jeff Adrien,F,28,MIN,17,0,12.6,1.1,...,12.9,14.1,0.2,0.2,0.4,0.093,-2.6,0.8,-1.8,0.0
4,4,2015,Arron Afflalo,G,29,TOT,60,54,32.5,5.0,...,10.9,19.6,1.4,0.7,2.1,0.051,-0.2,-1.4,-1.6,0.2

#### #4. Check out the shape of the data set.

In [11]:
nba_df.shape

(478, 50)

#### #5. Run some summary stats on the data set with the `describe()` function.

In [13]:
nba_df.describe()

,Unnamed: 0,season_end,age,g,gs,mp,fg,fga,fg_,x3p,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
count,478.000000,478.0,478.000000,478.000000,478.000000,478.000000,478.000000,478.000000,478.000000,478.000000,...,478.000000,478.000000,478.000000,478.000000,478.000000,478.000000,478.000000,478.000000,478.000000,478.000000
mean,238.500000,2015.0,26.573222,42.104603,19.874477,20.045607,3.018201,6.847699,0.429230,0.630544,...,13.424268,18.915272,1.055858,0.971339,2.027197,0.073575,-1.396862,-0.495816,-1.892678,0.485983
std,138.130976,0.0,4.219585,18.950602,22.170034,9.313441,2.052790,4.386828,0.111007,0.665808,...,6.559989,5.493491,1.589667,0.876932,2.243138,0.133530,4.251216,2.299572,5.116001,1.013097
min,0.000000,2015.0,19.000000,1.000000,0.000000,0.700000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,-2.100000,-0.100000,-0.800000,-1.059000,-36.800000,-13.500000,-50.300000,-1.000000
25%,119.250000,2015.0,23.000000,27.000000,0.000000,12.600000,1.425000,3.400000,0.391000,0.000000,...,10.000000,14.800000,0.000000,0.200000,0.300000,0.040250,-2.800000,-1.600000,-3.300000,-0.100000
50%,238.500000,2015.0,26.000000,47.000000,10.500000,19.850000,2.700000,5.900000,0.432000,0.450000,...,12.900000,18.400000,0.600000,0.800000,1.400000,0.082500,-1.000000,-0.500000,-1.300000,0.100000
75%,357.750000,2015.0,29.000000,59.000000,39.000000,28.175000,4.275000,9.600000,0.481750,1.000000,...,15.900000,21.900000,1.600000,1.500000,3.000000,0.123000,0.500000,0.875000,0.500000,0.700000
max,477.000000,2015.0,38.000000,66.000000,66.000000,38.900000,9.500000,21.400000,1.000000,3.400000,...,100.000000,45.900000,9.500000,4.300000,13.000000,1.489000,28.300000,6.500000,15.100000,6.200000

#### #6. Sort the data set in on the `players` column in alphabetical order.

In [15]:
f1=nba_df.sort_values('player')
f1

,Unnamed: 0,season_end,player,pos,age,bref_team_id,g,gs,mp,fg,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
359,359,2015,A.J. Price,G,28,TOT,21,0,13.3,2.3,...,8.9,23.6,0.2,0.2,0.4,0.072,0.5,-2.8,-2.4,0.0
60,60,2015,Aaron Brooks,G,30,CHI,65,9,21.0,3.9,...,15.5,25.7,1.1,1.0,2.1,0.073,0.7,-2.8,-2.1,0.0
166,166,2015,Aaron Gordon,F,19,ORL,30,6,15.2,1.9,...,17.0,15.9,0.3,0.3,0.6,0.066,-2.5,-0.5,-3.1,-0.1
348,348,2015,Adreian Payne,F,23,TOT,12,3,19.7,2.3,...,13.6,17.7,-0.3,0.1,-0.1,-0.024,-5.8,-2.5,-8.3,-0.4
212,212,2015,Al Horford,C,28,ATL,60,60,30.8,6.8,...,9.1,22.1,4.6,3.0,7.5,0.195,1.7,2.7,4.5,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,199,2015,Xavier Henry,F,23,LAL,9,0,9.6,0.3,...,11.3,13.7,-0.1,0.0,-0.1,-0.030,-5.3,-2.3,-7.6,-0.1
261,261,2015,Zach LaVine,G,19,MIN,57,23,20.4,2.9,...,21.3,20.6,-0.9,0.2,-0.7,-0.029,-2.9,-2.2,-5.0,-0.9
366,366,2015,Zach Randolph,F,33,MEM,53,53,32.6,6.6,...,12.4,24.5,2.6,2.9,5.5,0.153,0.2,0.8,1.0,1.3
340,340,2015,Zaza Pachulia,C,30,MIL,54,26,22.5,2.9,...,18.7,18.9,0.1,2.0,2.1,0.084,-2.2,2.0,-0.2,0.6
125,125,2015,Zoran Dragic,G,25,TOT,8,0,2.3,0.3,...,0.0,22.6,0.0,0.0,0.0,-0.056,-1.9,-5.3,-7.2,0.0

#### #7. Filter the data set. Create three sub DataFrames from the `position` column for `G`, `F`, and `C`.

In [17]:
nba_g=nba_df.value_counts('pos')
nba_g

pos
G    200
F    199
C     79
Name: count, dtype: int64

In [21]:
nba_df_G=nba_df[nba_df['pos'] == 'G']
nba_df_G

,Unnamed: 0,season_end,player,pos,age,bref_team_id,g,gs,mp,fg,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
1,1,2015,Jordan Adams,G,20,MEM,18,0,7.3,1.0,...,15.9,17.7,0.0,0.2,0.2,0.076,-2.3,1.8,-0.5,0.0
4,4,2015,Arron Afflalo,G,29,TOT,60,54,32.5,5.0,...,10.9,19.6,1.4,0.7,2.1,0.051,-0.2,-1.4,-1.6,0.2
10,10,2015,Tony Allen,G,33,MEM,54,36,25.6,3.5,...,14.1,16.4,0.8,2.6,3.4,0.118,-0.3,3.6,3.2,1.8
14,14,2015,Alan Anderson,G,32,BRK,62,19,23.8,2.5,...,11.8,13.7,1.3,0.9,2.1,0.070,-0.2,-0.3,-0.5,0.6
17,17,2015,Giannis Antetokounmpo,G,20,MIL,63,53,30.4,4.6,...,16.4,19.7,1.6,3.2,4.8,0.121,-1.6,2.6,1.0,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465,465,2015,Mo Williams,G,32,TOT,51,29,29.4,4.9,...,16.2,23.6,2.0,0.3,2.4,0.075,2.7,-3.8,-1.2,0.3
469,469,2015,Nate Wolters,G,23,TOT,21,0,11.8,1.0,...,17.9,13.3,-0.4,0.2,-0.2,-0.037,-5.9,0.1,-5.8,-0.2
472,472,2015,Tony Wroten,G,21,PHI,30,15,29.8,5.8,...,18.0,30.7,-0.6,0.8,0.2,0.012,0.4,-1.8,-1.4,0.1
473,473,2015,James Young,G,19,BOS,27,0,10.9,1.1,...,3.9,15.3,0.1,0.2,0.2,0.040,-1.9,-2.2,-4.1,-0.2
474,474,2015,Nick Young,G,29,LAL,42,0,23.8,4.1,...,7.5,26.0,1.1,0.1,1.2,0.059,1.0,-4.2,-3.2,-0.3

In [23]:
nba_df_F=nba_df[nba_df['pos'] == 'F']
nba_df_F

,Unnamed: 0,season_end,player,pos,age,bref_team_id,g,gs,mp,fg,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
0,0,2015,Quincy Acy,F,24,NYK,52,21,19.2,2.2,...,15.1,14.7,0.6,0.5,1.0,0.050,-2.6,-0.7,-3.4,-0.3
3,3,2015,Jeff Adrien,F,28,MIN,17,0,12.6,1.1,...,12.9,14.1,0.2,0.2,0.4,0.093,-2.6,0.8,-1.8,0.0
6,6,2015,Furkan Aldemir,F,23,PHI,25,1,10.7,0.6,...,21.1,7.8,0.3,0.4,0.7,0.127,-2.9,3.1,0.2,0.2
8,8,2015,LaMarcus Aldridge,F,29,POR,54,54,36.2,9.1,...,7.3,29.9,3.3,3.2,6.5,0.161,-0.4,0.3,-0.1,0.9
9,9,2015,Lavoy Allen,F,25,IND,47,0,19.6,2.7,...,10.0,15.2,1.5,1.4,2.9,0.152,-0.5,2.4,1.9,0.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466,466,2015,Reggie Williams,F,28,SAS,7,0,4.9,0.6,...,5.9,22.6,-0.1,0.0,0.0,-0.062,-4.7,-3.5,-8.2,-0.1
467,467,2015,Shawne Williams,F,28,TOT,50,22,19.5,2.2,...,8.0,14.6,1.3,0.7,1.9,0.096,0.5,-0.9,-0.4,0.4
470,470,2015,Brandan Wright,F,27,TOT,60,0,17.2,2.9,...,6.5,13.8,3.6,1.3,4.9,0.226,2.1,2.2,4.2,1.6
471,471,2015,Dorell Wright,F,29,POR,35,1,10.9,1.3,...,10.3,17.2,0.5,0.6,1.1,0.139,0.1,1.0,1.1,0.3
475,475,2015,Thaddeus Young,F,26,TOT,58,50,31.8,5.9,...,9.7,21.3,1.4,1.1,2.4,0.064,0.4,-0.1,0.3,1.1

In [25]:
nba_df_C=nba_df[nba_df['pos'] == 'C']
nba_df_C

,Unnamed: 0,season_end,player,pos,age,bref_team_id,g,gs,mp,fg,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
2,2,2015,Steven Adams,C,21,OKC,51,50,24.2,3.0,...,19.2,14.8,1.0,1.8,2.8,0.109,-2.0,2.0,-0.1,0.6
5,5,2015,Alexis Ajinca,C,26,NOP,51,6,14.0,2.8,...,15.3,20.8,1.8,0.9,2.7,0.181,0.4,0.2,0.7,0.5
7,7,2015,Cole Aldrich,C,26,NYK,45,12,15.9,2.3,...,15.5,17.9,0.4,0.9,1.3,0.089,-2.6,2.3,-0.3,0.3
13,13,2015,Chris Andersen,C,36,MIA,46,18,19.5,1.9,...,11.3,11.7,1.8,1.1,3.0,0.159,-1.0,2.2,1.3,0.7
19,19,2015,Joel Anthony,C,32,DET,32,0,5.8,0.5,...,15.9,8.9,0.2,0.3,0.5,0.123,-4.5,3.9,-0.6,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
443,443,2015,Nikola Vucevic,C,24,ORL,57,57,34.4,8.6,...,10.4,25.9,3.9,1.9,5.8,0.143,0.9,-0.3,0.6,1.3
456,456,2015,Hassan Whiteside,C,25,MIA,35,20,22.0,4.7,...,11.6,21.3,2.1,1.6,3.7,0.231,-1.5,0.3,-1.2,0.1
468,468,2015,Jeff Withey,C,24,NOP,31,0,6.3,0.8,...,9.0,18.2,0.4,0.2,0.6,0.140,-2.1,-0.9,-3.0,0.0
476,476,2015,Cody Zeller,C,22,CHO,61,44,24.1,2.8,...,12.3,15.6,1.7,2.2,3.9,0.129,-1.9,2.5,0.7,1.0
477,477,2015,Tyler Zeller,C,25,BOS,62,39,20.8,3.9,...,10.5,19.1,3.2,1.3,4.5,0.167,0.2,0.4,0.7,0.9

#### #8.  Run `describe()` on these new DataFrames. Compare the mean field goals (the `fg` column) between positions.

In [27]:
nba_df_G.describe()
nba_df_F.describe()
nba_df_C.describe()

,Unnamed: 0,season_end,age,g,gs,mp,fg,fga,fg_,x3p,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
count,79.000000,79.0,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,...,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000
mean,236.240506,2015.0,26.759494,42.012658,23.620253,19.126582,2.989873,5.922785,0.495608,0.058228,...,15.159494,17.755696,1.217722,1.239241,2.460759,0.097392,-2.418987,0.950633,-1.470886,0.513924
std,136.163007,0.0,3.810294,19.005056,22.214747,8.937629,2.060595,4.075409,0.120526,0.211592,...,5.933035,5.592709,1.431402,0.986371,2.240674,0.114917,3.832823,2.003578,4.727881,0.926495
min,2.000000,2015.0,20.000000,2.000000,0.000000,2.800000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,-1.000000,0.000000,-0.300000,-0.738000,-28.000000,-5.700000,-28.800000,-0.600000
25%,134.000000,2015.0,24.000000,29.500000,2.500000,12.700000,1.500000,2.850000,0.460500,0.000000,...,12.150000,13.650000,0.200000,0.300000,0.600000,0.076000,-3.250000,-0.300000,-2.700000,-0.100000
50%,244.000000,2015.0,26.000000,46.000000,18.000000,19.200000,2.800000,5.300000,0.505000,0.000000,...,15.300000,17.900000,0.800000,1.200000,2.100000,0.115000,-1.900000,1.100000,-0.900000,0.200000
75%,345.000000,2015.0,29.500000,58.500000,43.500000,25.900000,4.100000,7.600000,0.551000,0.000000,...,17.550000,21.150000,1.850000,1.800000,3.650000,0.146000,-0.200000,2.300000,0.750000,0.700000
max,477.000000,2015.0,37.000000,65.000000,64.000000,35.400000,8.600000,17.400000,0.857000,1.400000,...,43.200000,35.700000,6.100000,4.100000,9.900000,0.231000,2.100000,5.500000,5.800000,3.600000

In [29]:
nba_df_G['fg'].mean()

3.2

In [33]:
nba_df_F['fg'].mean()

2.8467336683417086

In [35]:
nba_df_C['fg'].mean()

2.9898734177215194

The end!

#### Great job!